### ISSUE TITLE
where is ProcessPopSize()?

### ISSUE THREAD

**Issue by chlangley** [revbayes/RevGadgets#16]
In working thru the coalescent tutorials, https://revbayes.github.io/tutorials/coalescent/ I hit upon this issue:

```
> df <- processPopSizes(population_size_log, burnin = burnin, probs = probs, summary = summary, num_grid_points = num_grid_points, max_age = max_age_iso)
Error in processPopSizes(population_size_log, burnin = burnin, probs = probs,  :
  could not find function "processPopSizes"
```

In searching this (all) GitHub I don't find the code for "processPopSizes" .  
I also noted the reference to legacy versions of RevGadgets needed for unspecified tutorials.  I tried installing that referenced legacy version.  But the function is not defined in that version either.  

No doubt I am lost in the mirror room of namespaces. 

Please point me to the appropriate exit.

Thanks in advance.
Chuck

**Comment by cmt2** [comment]
Dear Chuck,

Since this tutorial is still under development, the population size
plotting features are available only in a development branch of RevGadgets
@dev_pop_size (for example, here's the code for the processing script:
https://github.com/revbayes/RevGadgets/blob/dev_pop_size/R/processPopSizes.R
)

The instructions at the top of the tutorial (screenshot below) will guide
you through installing that development branch of RevGadgets with devtools;
you should then be able to use these functions. Please let us know if you
give that a try and you still have questions or if other issues come up.

cheers,
Carrie
[image: Screen Shot 2023-02-20 at 3.54.52 PM.png]

-------------------
Carrie M. Tribble, PhD <http://carrietribble.weebly.com/> (she/her)
NSF Postdoctoral Fellow, Zenil-Ferguson Lab <https://roszenil.github.io/>
University of Hawaiʻi at Mānoa

**Comment by chlangley** [comment]
Dear Carrie:

thanks for getting back so quickly.

I think I tried the directions for installing the development version.  I’ll check again tonight.

But thanks for the link to the function.


Do you know if anyone is looking to make a model coalescent process with several sister taxa sequences, linking intertax divergence with one or more population samples?

Thanks again.

Cheers
Chuck

**Comment by cmt2** [comment]
Hey Chuck,

That's a great question for @hoehna! Hopefully he can chime in here, or feel free to reach out to him directly.

cheers,
Carrie
